fix: capitalization of thorium in repo urls
Alex313031/thorium pull request #223
Opened 2023-09-21 17:18 UTC by qoijjj

fix: capitalization of thorium in repo urls

2023-09-21 17:23 UTC, gz83 requested changes
Unable to approve and merge, the patch now contains conflicts and errors, please submit again.

Tip: If you need to submit a PR in the future, please be sure to make modifications according to the requirements of the repo maintainer.

2023-09-21 17:33 UTC, qoijjj commented
> Unable to approve and merge, the patch now contains conflicts and errors, please submit again.

Fixed

> Tip: If you need to submit a PR in the future, please be sure to make modifications according to the requirements of the repo maintainer(or collaborator).

Please refrain from your continued condescending remarks. Not only does it impede proper understanding, as I have no idea what you're referring to, but it makes for a toxic environment.

2023-09-21 17:41 UTC, gz83 commented
Please reconfirm that all modifications in the patch are correct. You can make modifications according to the repo address under Alex's account. Be sure to note that the replaced repo is still in use. Because some adjustments were made to some repo before.

This is not a condescending comment, my purpose is just to let you notice the problems in your PR, and I have made it very clear in previous PRs. If my remarks make you uncomfortable, I apologize, but I will still have certain review principles.

This topic ends here and requires no further discussion.

In addition, Alex will be the final reviewer and merger of each PR, and I will only do the preliminary review for the time being.

@qoijjj

2023-09-21 17:43 UTC, qoijjj commented
> Please reconfirm that all modifications in the patch are correct. You can make modifications according to the repo address under Alex's account. 

That is what I have done

> Be sure to note that the replaced repo is still in use. Because some adjustments were made to some repo before.

I am not clear what this means

2023-09-21 17:45 UTC, qoijjj commented
Ah I see now, there are other repos that are capitalized. Fixing now.

2023-09-21 17:51 UTC, qoijjj commented
Fixed, let me know if I missed any.

2023-10-08 06:51 UTC, gz83 requested changes
You need to address all comments and discuss them with us. Additionally, you will need to wait for further review from Alex.

2023-10-08 06:51 UTC, gz83 commented on arm/README.md
> +__IMPORTANT:__ For a [Raspberry Pi](https://www.raspberrypi.org/) build (ARM64), the contents of [raspi_arm.gni](https://github.com/Alex313031/thorium/blob/main/arm/raspi_arm.gni) should be manually
nit:
https://github.com/Alex313031/thorium/blob/main/arm/raspi_args.gn ->https://github.com/Alex313031/thorium/blob/main/arm/raspi/raspi_args.gn

2023-10-08 06:51 UTC, gz83 commented on docs/WIN_CROSS_BUILD_INSTRUCTIONS.txt
> +Download the latest .zip > https://github.com/Alex313031/thorium/archive/refs/heads/main.zip
nit:
I think we can consider deleting this line, because when downloading the .zip compressed package directly, the submodule files cannot be obtained

2023-10-08 06:51 UTC, gz83 commented on docs/WIN_INSTRUCTIONS.txt
> +git clone --recursive https://github.com/Alex313031/thorium.git or download the .zip and unpack it there > https://github.com/Alex313031/Thorium/archive/refs/heads/main.zip
ditto

2023-10-08 06:51 UTC, gz83 commented on infra/APPIMAGE/README.md
> +&ndash; The [*Thorium.yml*](https://github.com/Alex313031/thorium/blob/main/infra/APPIMAGE/Thorium.yml) file was modeled after the official Chromium one from here > https://github.com/AppImage/pkg2ap
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/APPIMAGE/Thorium.yml
> +# Official Thorium builds can be downloaded from https://github.com/Alex313031/thorium/releases
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/Arch_Linux/.SRCINFO
> +	source = https://github.com/Alex313031/thorium/releases/download/M111.0.5563.111/thorium-browser_111.0.5563.111-1_amd64.deb
nit:
I think we can update the version number here

2023-10-08 06:51 UTC, gz83 commented on infra/Arch_Linux/PKGBUILD
> +source=("https://github.com/Alex313031/thorium/releases/download/M${pkgver}/${_pkgname}_${pkgver}-1_amd64.deb"
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/BUGS.md
> +<img src="https://github.com/Alex313031/thorium/blob/main/logos/STAGING/robot_256.png">
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/BUILDING_OLD.md
> +- __UPDATE:__ For Windows and Windows [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2), I made new dedicated instructions. If you are building on Windows
nit:

1. https://github.com/Alex313031/thorium/blob/main/misc/WIN_INSTRUCTIONS.txt ->https://github.com/Alex313031/thorium/blob/main/docs/WIN_INSTRUCTIONS.txt

2. https://github.com/Alex313031/thorium/blob/main/misc/WIN_CROSS_BUILD_INSTRUCTIONS.txt ->https://github.com/Alex313031/thorium/blob/main/docs/WIN_CROSS_BUILD_INSTRUCTIONS.txt

2023-10-08 06:51 UTC, gz83 commented on infra/DEBUG/DEBUG_SHELL_README.md
> +## Building <img src="https://github.com/Alex313031/thorium/blob/main/logos/NEW/build_light.svg#gh-dark-mode-only"> <img src="https://github.com/Alex313031/thorium/blob/main/logos/NEW/build_dark.svg#
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/DEBUG/README.md
> +<img src="https://github.com/Alex313031/thorium/blob/main/logos/NEW/thorium_infra_256.png" width="200">
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> + - The [android_args.gn](https://github.com/Alex313031/thorium/blob/main/infra/android_args.gn) is for Android ARM64. > https://chromium.googlesource.com/chromium/src/+/main/docs/android_build_instru
nit:

The [android_args.gn](https://github.com/Alex313031/thorium/blob/main/infra/android_args.gn) is for Android ARM64. https://chromium.googlesource.com/chromium/src/+/main/docs/android_build_instructions.md ->
The [android_ARM64_args.gn](https://github.com/Alex313031/thorium/blob/main/arm/android/android_ARM64_args.gn) is for Android ARM64.  https://chromium.googlesource.com/chromium/src/+/main/docs/android_build_instructions.md

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> + - The [cros_args.gn](https://github.com/Alex313031/thorium/blob/main/infra/cros_args.gn) is for ChromiumOS on Linux. > https://chromium.googlesource.com/chromium/src/+/main/docs/chromeos_build_instr
nit:

https://github.com/Alex313031/thorium/blob/main/infra/cros_args.gn -> https://github.com/Alex313031/thorium/blob/main/other/CrOS/cros_args.gn

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> + - The [mac_args.gn](https://github.com/Alex313031/thorium/blob/main/infra/mac_args.gn) is for x64 macs. (See [Thorium Special](https://github.com/Alex313031/Thorium-Special) for ARM64 M1 args.gn.)
nit:

1. https://github.com/Alex313031/thorium/blob/main/infra/mac_args.gn -> https://github.com/Alex313031/thorium/blob/main/other/Mac/mac_args.gn

2. See [Thorium Special](https://github.com/Alex313031/Thorium-Special) -> See [mac_ARM_args.gn](https://github.com/Alex313031/thorium/blob/main/other/Mac/mac_ARM_args.gn)

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> + - The [win_args.gn](https://github.com/Alex313031/thorium/blob/main/infra/win_args.gn) is for Windows x64 \
nit:

https://github.com/Alex313031/thorium/blob/main/infra/win_args.gn -> https://github.com/Alex313031/thorium/blob/main/win_args.gn

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> +&nbsp;&ndash; The [WIN_INSTRUCTIONS.txt](https://github.com/Alex313031/thorium/blob/main/infra/WIN_INSTRUCTIONS.txt) and [WIN_CROSS_BUILD_INSTRUCTIONS.txt](https://github.com/Alex313031/thorium/blob/
nit:

1. https://github.com/Alex313031/thorium/blob/main/infra/WIN_INSTRUCTIONS.txt -> https://github.com/Alex313031/thorium/blob/main/docs/WIN_INSTRUCTIONS.txt
2. https://github.com/Alex313031/thorium/blob/main/infra/WIN_CROSS_BUILD_INSTRUCTIONS.txt -> https://github.com/Alex313031/thorium/blob/main/docs/WIN_CROSS_BUILD_INSTRUCTIONS.txt

2023-10-08 06:51 UTC, gz83 commented on infra/README.md
> +&nbsp;&ndash; The [thorium_devel_bookmarks.html](https://github.com/Alex313031/thorium/blob/main/infra/thorium_devel_bookmarks.html) file contain the bookmarks I use for Thorium development and rebas
nit:

The [thorium_devel_bookmarks.html](https://github.com/Alex313031/thorium/blob/main/infra/thorium_devel_bookmarks.html) -> The [THORIUM_DEV_BOOKMARKS.html](https://github.com/Alex313031/thorium/blob/main/infra/THORIUM_DEV_BOOKMARKS.html)

2023-10-08 06:51 UTC, gz83 commented on infra/install_deps.sh
> +git clone --recursive https://github.com/Alex313031/thorium.git &&
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/portable/make_portable_linux.sh
> +printf "${bold}${RED} - Make sure to rename the .zip properly as per https://github.com/Alex313031/thorium/discussions/28#discussioncomment-3031799 ${c0}\n" &&
LGTM

2023-10-08 06:51 UTC, gz83 commented on infra/portable/make_portable_win.sh
> +printf "${bold}${RED} - Make sure to rename the .zip properly as per https://github.com/Alex313031/thorium/discussions/28#discussioncomment-3031799 ${c0}\n" &&
LGTM

2023-10-08 06:51 UTC, gz83 commented on logos/NEW/mac/gen/README.md
> +<img src="https://github.com/Alex313031/thorium/blob/main/logos/NEW/mac/apple.png" width="200">
LGTM

2023-10-08 06:51 UTC, gz83 commented on logos/README.md
> +*LICENSING*: The Chromium Logo is licensed under Chromium's BSD-Style [License](https://github.com/Alex313031/thorium/blob/main/infra/CHROMIUM_LICENSE.txt), and some logos like the "bulb" and "build"
nit:

https://github.com/Alex313031/thorium/blob/main/infra/CHROMIUM_LICENSE.txt -> https://github.com/Alex313031/thorium/blob/main/infra/CHROMIUM_LICENSE

2023-10-08 06:51 UTC, gz83 commented on other/WIN7/about_version.html
> +        <div id="company"><a target="_blank" rel="noopener" href="https://github.com/Alex313031/thorium">$i18n{company}</a></div>
LGTM

2023-10-08 06:51 UTC, gz83 commented on pak_src/README.md
> +<img src="https://github.com/Alex313031/thorium/blob/main/logos/STAGING/pak.png">
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/ash/webui/help_app_ui/resources/app.html
> +    <br/>‣ Kernel configuration and <a title="About Linux Firmware" rel="noopener" target="_blank" href="https://wiki.gentoo.org/wiki/Linux_firmware">Linux firmware</a> to support as many devices as
nit:

thoriumOS -> ThoriumOS

2023-10-08 06:51 UTC, gz83 commented on src/chrome/app/resources/manpage.1.in
> +http://code.google.com/p/chromium/issues/list & https://github.com/Alex313031/thorium/issues
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/chrome/installer/linux/common/chromium-browser/chromium-browser.appdata.xml
> +  <url type="bugtracker">https://github.com/Alex313031/thorium/issues</url>
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/chrome/installer/linux/common/chromium-browser/chromium-browser.info
> +PRODUCTURL="https://github.com/Alex313031/thorium"
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/components/neterror/README.md
> +This dir also includes the scripts and images for the Thorium Dino game.&nbsp;&nbsp;<img src="https://github.com/Alex313031/thorium/blob/main/logos/STAGING/dino_32px.png">
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/components/version_ui/resources/about_version.html
> +        <div id="company"><a target="_blank" rel="noopener" href="https://github.com/Alex313031/thorium">$i18n{company}</a></div>
LGTM

2023-10-08 06:51 UTC, gz83 commented on src/third_party/pak/README.chromium
> +URL: https://github.com/Alex313031/thorium/tree/main/pak_src
LGTM

2023-10-08 06:51 UTC, gz83 commented on win_scripts/README.md
> +## Windows Build Scripts <img src="https://github.com/Alex313031/thorium/blob/main/logos/STAGING/winflag_animated.gif" width="64">
LGTM

2023-10-08 06:56 UTC, gz83 commented
CC:@Alex313031

2023-10-10 12:47 UTC, Alex313031 commented
@gz83 @qoijjj Could one of you resolve that .sh conflict. 

After that, is it ready to merge?

2023-10-10 13:01 UTC, Alex313031 approved these changes

2023-10-10 13:02 UTC, merged